version: '3.5'
services:
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator.Dockerfile
    image: bc-orch/orchestrator
    container_name: orchestrator
    environment:
      - RABBITMQ=rabbitmq
      - LOG_LEVEL=INFO
    networks:
      - benchmark
    depends_on:
      - rabbitmq
  host_manager:
    build:
      context: .
      dockerfile: host_manager.Dockerfile
    image: bc-orch/host-manager
    container_name: host_manager
    environment:
      - RABBITMQ=rabbitmq
      - LOG_LEVEL=INFO
    privileged: true
    networks:
      - benchmark
    depends_on:
      - rabbitmq
  geth_manager:
    build:
      context: .
      dockerfile: geth_manager.Dockerfile
    image: bc-orch/geth-manager
    container_name: geth_manager
    environment:
      - RABBITMQ=rabbitmq
      - LOG_LEVEL=INFO
    networks:
      - benchmark
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq
    restart: on-failure
    networks:
      - benchmark
networks: 
  benchmark:
    name: benchmark