version: '3.5'
services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile
    image: bc-orch-controller
    container_name: orch-controller
    ports:
      - "3000:5000"
    volumes:
      - /home/ubuntu:/root  # This must not change, so you need to have a ubuntu user with ssh key already configured and unlocked
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=INFO      # Only INFO and DEBUG are supported 
      - SERVER_IP           # The IP address at which the controller can be reached from the hosts
    networks:
      - benchmark
networks: 
  benchmark:
    name: benchmark