version: '3.5'
services:
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    image: bc-orch-orchestrator
    container_name: orchestrator
    environment:
      - RABBITMQ=rabbitmq
      - LOG_LEVEL=INFO
    restart: on-failure
    networks:
      - benchmark
  host_manager:
    build:
      context: ./resource_manager/host_manager
      dockerfile: Dockerfile
    image: bc-orch-host-manager
    container_name: host_manager
    environment:
      - RABBITMQ=rabbitmq
      - LOG_LEVEL=INFO
    restart: on-failure
    networks:
      - benchmark
  rabbitmq:
    image: rabbitmq
    networks:
      - benchmark
networks: 
  benchmark:
    name: benchmark