version: '3'

services:
  node:
    image: russanto/bm-btc-multichain
    ports:
      - "7410-7411:7410-7411"
    volumes:
      - ./node:/root/.multichain/benchmark
    # restart: on-failure
    command: multichaind benchmark
  controller:
    image: russanto/bm-btc-multichain-controller
    ports:
      - "8080:8080"
    volumes:
      - ./node:/root/benchmark
    command: "python3 /root/node-controller.py"
    environment:
      - NODE_HOST=node
      - CHAIN_NAME=benchmark # must be the same as pointed in root folder
    # restart: on-failure
    depends_on:
      - node