version: '3'

services:
  node:
    image: russanto/bm-btc-multichain
    ports:
      - "7410-7411:7410-7411"
    volumes:
      - ${CHAIN_DATADIR}:/root/.multichain/${CHAIN_NAME}
    # restart: on-failure
    command: multichaind ${CHAIN_NAME}@${SEED_NODE_HOST}:${SEED_NODE_PORT} -logtimemillis
  controller:
    image: russanto/bm-btc-multichain-controller
    ports:
      - "8080:8080"
    volumes:
      - ${CHAIN_DATADIR}:/root/${CHAIN_NAME}
    command: python3 /root/node-controller.py
    environment:
      - NODE_HOST=node
      - CHAIN_NAME # must be the same as pointed in root folder
    # restart: on-failure
    depends_on:
      - node
  logger:
    image: russanto/bm-btc-multichain-logger
    ports:
      - "80:80"
    volumes:
      - ${CHAIN_DATADIR}:/root/${CHAIN_NAME}
    command: /bin/sh -c "tail -f /root/${CHAIN_NAME}/debug.log | /root/client http://${LOG_COLLECTOR_HOST}:${LOG_COLLECTOR_PORT} ${NODE_NAME} node"
    depends_on:
      - node