# This config should be placed in following path:
#   ~/.local/share/io.parity.ethereum/config.toml

[parity]
# Custom chain
chain = "benchmark"
# Parity continously syncs the chain
mode = "active"
# No updates will be auto-installed
auto_update = "none"
# Disables auto downloading of new releases. Not recommended.
no_download = true
# Blockchain and settings will be stored in ~.
base_path = "."
# Don't save pending local transactions to disk to be restored whenever the node restarts.
no_persistent_txqueue = true

[network]
# Parity won't attempt detect you public IP address
nat = "none"
# Enable or disable new peers discovery.
discovery = false

[rpc]
#  JSON-RPC will be listening for connections on IP all.
interface = "all"
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "pubsub", "net", "parity", "private", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub", "personal", "parity_set"]
# Threads for handling incoming connections for HTTP JSON-RPC server.
server_threads = 2
# Turn on additional processing threads for JSON-RPC servers (all transports). Setting this to a non-zero value allows parallel execution of cpu-heavy queries.
processing_threads = 2

[websockets]
# UI won't work and WebSockets server will be not available.
disable = true

[mining]
# Account address to receive reward when block is mined.
# author = ""
# Account to sign consensus messages and issue blocks for non-PoW chains.
# engine_signer = ""
# Prepare a block to seal even when there are no miners connected.
force_sealing = true
# You will be paid $0.000001 for a basic transaction - Minimum gas price will be set accordingly.
usd_per_tx = "0.000001"
# Minimum amount of Wei per GAS to be paid for a transaction to be accepted for mining. Overrides --usd-per-tx.
min_gas_price = 1
# Maximum number of transactions per sender in the queue. By default it's 1% of the entire queue, but not less than 16.
tx_queue_per_sender = 1000
# Maximum amount of memory that can be used by the transaction queue. Setting this parameter to 0 disables limiting.
tx_queue_mem_limit = 0

[misc]
# Logs will be stored at /home/parity/logs.
log_file = "/home/parity/logs"